Feature/exercicio 9
JeanDMAlves/angular-boilerplate pull request #1
Opened 2021-11-20 19:13 UTC by JeanDMAlves

@matheus-yudi-helpper 
Implementado o CRUD

2021-11-20 20:27 UTC, matheus-yudi-helpper requested changes

2021-11-20 20:27 UTC, matheus-yudi-helpper commented on src/app/@theme/interfaces/dadosCliente.ts
> +    "id":number,
Não precisa colocar aspas nas chaves da interface e adicione um espaço entre a chave e o valor para melhorar a legibilidade.

Ao declarar uma `interface,` `enum` ou `type` é uma boa prática utilizar um prefixo correspondente para ajudar na legibilidade e não depender do intellisense para identificar qual tipo está sendo manuseado. Por exemplo:

```ts
IPerson // interface de Person (prefixo 'I' maiúsculo);

TProperty // type Property (prefixo 'T' maiúsculo);

EnumPersonDocument // enum dos tipos de documento de uma Person (prefixo 'Enum' maiúsculo);
```

2021-11-20 20:27 UTC, matheus-yudi-helpper commented on src/app/@theme/styles/styles.scss
> +:root {
Usar apenas um idioma para declarar as classes e variáveis css também.

2021-11-20 20:27 UTC, matheus-yudi-helpper commented on src/app/@theme/components/update-client-data/update-client-data.component.ts
> +        const item = lista.find(element => element.id == id);
Não ficaria mais intuitivo nomear o método como searchById, já que ele realiza uma busca pelo id e retorna o item todo e não somente o id?

Também, não precisa atribuir na variável, pode retornar direto.

2021-11-20 20:27 UTC, matheus-yudi-helpper commented on src/app/@theme/components/update-client-data/update-client-data.component.ts
> +        return JSON.parse(this.storage.readItem('clientes'));
Você poderia deixar o parse lá no service, aí não precisaria ter um método no componente só para isso.

2021-11-20 20:27 UTC, matheus-yudi-helpper commented on src/app/@theme/components/update-client-data/update-client-data.component.ts
> +            const indexClient = listaClients.indexOf(client);
Não precisa buscar novamente, uma vez que o **searchById** já te retorna a referência do objeto, basta alterá-lo.

2021-11-20 20:27 UTC, matheus-yudi-helpper commented on src/app/@theme/components/delete-client-data/delete-client-data.component.ts
> +            const indexClient = listaClients.indexOf(client);
O ideal quando se trabalho com objetos é realizar a busca por **findIndex** e verificar por um atributo em comum.

2021-11-20 20:27 UTC, matheus-yudi-helpper commented on src/app/@theme/components/update-client-data/update-client-data.component.html
> +        <label class="form-field_label" for="id-update">ID</label>
Para nomear os ids e classes do HTML, é uma boa prática manter todas as letras minúsculas e usar sublinhados (snake_case) ou hifens.

2021-11-20 20:27 UTC, matheus-yudi-helpper commented on src/app/@theme/interfaces/dadosCliente.ts
> +    "status":string
Você poderia criar um enum para o status do cliente.

2021-11-20 20:27 UTC, matheus-yudi-helpper commented on src/app/@theme/components/clientes/clientes.component.ts
> +
Quando se trabalha com observables, o ideal é se desinscrever do mesmo quando o componente for destruído. Para isso, guardamos a inscrição do retorno do `subscribe` em uma variável para podermos para de ouvir depois:

```ts
private storageObservable: Subscription;
  .
  .
  .
public ngOnInit(): void {
        this.storageObservable = this.storage.getObservable().subscribe(()=>{
            this.clientes = JSON.parse(this.storage.readItem('clientes'));
        });
    }

public ngOnDestroy(): void {
        // Adicionado o ? para evitar estourar erro caso a variável esteja vazia.
        this.storageObservable?.unsubscribe();
    }
```

2021-11-21 02:08 UTC, JeanDMAlves commented on src/app/@core/services/local-storage.service.ts
> +export class LocalStorageService {
Resolvido

2021-11-21 02:09 UTC, JeanDMAlves commented on src/app/@core/services/local-storage.service.ts
> +    public createItem(key:string, value: string): any{
Resolvido

2021-11-21 02:11 UTC, JeanDMAlves commented on src/app/@core/services/local-storage.service.ts
> +    public readItem(key:string): any{
Resolvido

2021-11-21 02:11 UTC, JeanDMAlves commented on src/app/@core/services/local-storage.service.ts
> +    //   public updateItem(key:string, alteration:string): any{
Feito

2021-11-21 02:12 UTC, JeanDMAlves commented on src/app/@core/services/local-storage.service.ts
> +    public deleteItem(key:string): any{
Feito

2021-11-21 02:40 UTC, JeanDMAlves commented on src/app/@theme/components/cadastro/cadastro.component.ts
> +export class CadastroComponent{
Feito

2021-11-21 20:05 UTC, merged